services:
  db:
    image: postgis/postgis:17-3.5
    container_name: global_camera_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: global_camera
      POSTGRES_USER: camera_admin
      POSTGRES_PASSWORD: camera_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: